### PR TITLE
Makefile

### PR DESCRIPTION
**Pull request by eylles**
the makefile is more flexible for installation as it allows to specify the installation directory with the PREFIX and DESTDIR variables, tho i'm not sure if leaving the default PREFIX as ```~/.local```
also i guess pip3 is a good default for PIPVER, still wondering if it is better that way or figure out how to get that from the OS in a makefile.

### CODE REVIEW

**Comment by eylles** [comment]
i was thinking maybe adding a script that manages installing wichcraft just like the install.sh script did, as in run a command to decide if pip3 or pip then install wichcraft, what do you think?.

**Comment by GideonWolfe** [comment]
Yeah I like this idea! If we find that any `pip` is on the system, we could attempt to grab the dependencies. Maybe we install with `--user` flag to avoid asking for root password?

**Comment by Genghius** [comment]
Bom dia, sera que voçe fala inglês?

**Comment by eylles** [comment]
@GideonWolfe i finally figured out how to make this work, the makefile not only will detect the right pip command to use but also warn if pip isn't installed, and of course no need to use sudo to install.

**Comment by eylles** [comment]
well, i can't think of anything else i could do to this makefile to improve it so for me this branch is as ready to merge as it could be.

**Comment by GideonWolfe** [comment]
Thanks for the contribution!

**Pull request merged**
